### ISSUE TITLE
Trying to update my blog entry

### ISSUE THREAD

**Issue by hacke1978** [PointCloudLibrary/blog#71]
Hi,
I just tried to make an update commit for my blog entry. I tried out after preparing the commit locally:
* push a new branch named `fb-update_simpletree` with this commit
* push directly to master

Both push attempts failed by receiving
```
remote: Permission to PointCloudLibrary/blog.git denied to hacke1978.
fatal: unable to access 'https://github.com/PointCloudLibrary/blog.git/': The requested URL returned error: 403
```

**Comment by jspricke** [comment]
You need to clone the repo to your own Github account and send a pull request.

**Comment by hacke1978** [comment]
Done now in:
https://github.com/PointCloudLibrary/blog/pull/72
